name: Firebase Staging Deploy

on:
  push:
    branches: [main]


jobs:
  firebase-stage-deploy:
    name: Firebase Development Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Node v14
        uses: actions/setup-node@master
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build React WebApp
        run: yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: tedx-nitrourkela
          channelId: blogstaging
          expires: 30d